dist: xenial
language: python
python:
- 3.6
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run black --check .
- poetry run flake8 .
- poetry run pytest tests
before_deploy:
- poetry build
- poetry config http-basic.pypi $PYPI_USERNAME $PYPI_PASSWORD
deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_TAG =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$"
