from typing import Any, Dict, Iterator, List, Tuple

JsonDict = Dict[str, Any]

class DataFrame:
    index: Index
    columns: Index
    def __init__(self, data: List[JsonDict] = None, index: List[int] = None): ...
    def copy(self) -> DataFrame: ...
    def drop(self, labels: str, axis: int, inplace: bool): ...
    def insert(self, loc: int, column: str, value: Index): ...
    def iterrows(self) -> Iterator[Tuple[int, Series]]: ...

class Series:
    def to_json(self) -> str: ...

class Index:
    name: str
    def __iter__(self) -> Iterator[str]: ...
