name: Release

on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install poetry and toml-cli
        run: |
          pip install --upgrade pip
          pip install poetry==1.1.4
          pip install toml-cli==0.1.3
      - name: Install npm
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install semantic-release
        run: npm install -g semantic-release@17 @semantic-release/exec@5
      - name: Run semantic-release
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: semantic-release
