name: Release

on:
  release:
    types: [published]

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Poetry
      uses: dschep/install-poetry-action@v1.2
    - name: Install dependencies
      run: poetry install --no-dev
    - name: Publish to PyPI
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
      run: poetry publish --build
